configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDhmYzI0NDM1ZWU3OWY2YjFkYTViZjA4NDc2ZDY1Y2M2NmM3MjQ5YWQ2ODg5NmM2OTY2MDQzNzc0MTc2MjNlZTBjYjRkMDljMmJjOTA2YTAzMTUxNDM0NTY0ZGNhNGYxNmY5YWNkYzc4NmJkOWJmYmIwNDFiMTdhNTgwOTFjM2Y=
