package com.nexaflow.billing.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAllPropertiesEquals(Subscription expected, Subscription actual) {
        assertSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAllUpdatablePropertiesEquals(Subscription expected, Subscription actual) {
        assertSubscriptionUpdatableFieldsEquals(expected, actual);
        assertSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAutoGeneratedPropertiesEquals(Subscription expected, Subscription actual) {
        assertThat(actual)
            .as("Verify Subscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionUpdatableFieldsEquals(Subscription expected, Subscription actual) {
        assertThat(actual)
            .as("Verify Subscription relevant properties")
            .satisfies(a -> assertThat(a.getOrganizationId()).as("check organizationId").isEqualTo(expected.getOrganizationId()))
            .satisfies(a -> assertThat(a.getPlanCode()).as("check planCode").isEqualTo(expected.getPlanCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionUpdatableRelationshipsEquals(Subscription expected, Subscription actual) {
        // empty method
    }
}
