package com.nexaflow.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InvitationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvitationAllPropertiesEquals(Invitation expected, Invitation actual) {
        assertInvitationAutoGeneratedPropertiesEquals(expected, actual);
        assertInvitationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvitationAllUpdatablePropertiesEquals(Invitation expected, Invitation actual) {
        assertInvitationUpdatableFieldsEquals(expected, actual);
        assertInvitationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvitationAutoGeneratedPropertiesEquals(Invitation expected, Invitation actual) {
        assertThat(actual)
            .as("Verify Invitation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvitationUpdatableFieldsEquals(Invitation expected, Invitation actual) {
        assertThat(actual)
            .as("Verify Invitation relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getInvitedAt()).as("check invitedAt").isEqualTo(expected.getInvitedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getAcceptedAt()).as("check acceptedAt").isEqualTo(expected.getAcceptedAt()))
            .satisfies(a -> assertThat(a.getInvitedByUserId()).as("check invitedByUserId").isEqualTo(expected.getInvitedByUserId()))
            .satisfies(a -> assertThat(a.getInvitedByLogin()).as("check invitedByLogin").isEqualTo(expected.getInvitedByLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvitationUpdatableRelationshipsEquals(Invitation expected, Invitation actual) {
        assertThat(actual)
            .as("Verify Invitation relationships")
            .satisfies(a -> assertThat(a.getOrganization()).as("check organization").isEqualTo(expected.getOrganization()));
    }
}
