package com.nexaflow.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MembershipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAllPropertiesEquals(Membership expected, Membership actual) {
        assertMembershipAutoGeneratedPropertiesEquals(expected, actual);
        assertMembershipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAllUpdatablePropertiesEquals(Membership expected, Membership actual) {
        assertMembershipUpdatableFieldsEquals(expected, actual);
        assertMembershipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAutoGeneratedPropertiesEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipUpdatableFieldsEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getUserLogin()).as("check userLogin").isEqualTo(expected.getUserLogin()))
            .satisfies(a -> assertThat(a.getUserEmail()).as("check userEmail").isEqualTo(expected.getUserEmail()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getJoinedAt()).as("check joinedAt").isEqualTo(expected.getJoinedAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipUpdatableRelationshipsEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership relationships")
            .satisfies(a -> assertThat(a.getOrganization()).as("check organization").isEqualTo(expected.getOrganization()));
    }
}
