# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: user-service
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDhmYzI0NDM1ZWU3OWY2YjFkYTViZjA4NDc2ZDY1Y2M2NmM3MjQ5YWQ2ODg5NmM2OTY2MDQzNzc0MTc2MjNlZTBjYjRkMDljMmJjOTA2YTAzMTUxNDM0NTY0ZGNhNGYxNmY5YWNkYzc4NmJkOWJmYmIwNDFiMTdhNTgwOTFjM2Y=
