# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: notification-service
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmFhMDU2Mjg2Y2I2MzAyMjQ5OWFhNDhkYjZiYzMzZThiYTUyMzNkOWU5MzRiZGU0MzEyYjQ4ZGVkYjM1NmUwYzZiZTUyNTI4MWNhOGRkZTQzNmU1ZjllZTAzMjM5MTBlYjdhNWQyMzBiMGYwNWMwMWI2ZTFiMzhkYzU3NjNhZDg=
