# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: billing-service
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODg5ODM2NGI1MzA4ZGVlMDhjZTNiYzdjZmU4ZDE4NTgzN2Y4YTE1NzYxZGM2MWI1NTM1ZjFhNDQ1OTBkMzI5NDgxZjA1NWYyM2QxNzdhNGQxZWJjYzA2MDFiOWYxMmY4ZTlkYTE3YTdkZWZkN2Y5NTY4ZGY5ODg1ODY2MGYzZjc=
