package com.nexaflow.project.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAllPropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertActivityLogAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAllUpdatablePropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertActivityLogUpdatableFieldsEquals(expected, actual);
        assertActivityLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAutoGeneratedPropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertThat(actual)
            .as("Verify ActivityLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogUpdatableFieldsEquals(ActivityLog expected, ActivityLog actual) {
        assertThat(actual)
            .as("Verify ActivityLog relevant properties")
            .satisfies(a -> assertThat(a.getOrganizationId()).as("check organizationId").isEqualTo(expected.getOrganizationId()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getPerformedBy()).as("check performedBy").isEqualTo(expected.getPerformedBy()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogUpdatableRelationshipsEquals(ActivityLog expected, ActivityLog actual) {
        // empty method
    }
}
