# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: project-service
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTI2MDFlZWE0MGQ2NTJhYjM3MmIwM2EwMjkyNTljMmIwNTQ5M2IwMWZmNGM3MjJhYTEzMjkyZGE3YmQ0NmIwYmViYTM5NDA0Nzc4Mzg0MWVhYTM1NTkxN2QxODBiZGM2MjE3ZTk2NTk3Y2Y4MTM5MmQ0ZjY4YjRhODY1ZjE4ZWU=
