configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGM3NjhlZTQzNGQ5MGQ5YjBiYTc5YzE1ZDJjNzZiNjRhZWM0OGI4ODc2NzhjYWQ2MmViYWMxYWU1M2U0NzFhNjgzOGI1NTZmYTBjNTgwODFmMjYwMDA1MjMxYzA4NGI5ZjJkNjc0MDdkODc5ZmVmODM0YWZkNDM0MDVmMTU5ZTU=
