configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTI2MDFlZWE0MGQ2NTJhYjM3MmIwM2EwMjkyNTljMmIwNTQ5M2IwMWZmNGM3MjJhYTEzMjkyZGE3YmQ0NmIwYmViYTM5NDA0Nzc4Mzg0MWVhYTM1NTkxN2QxODBiZGM2MjE3ZTk2NTk3Y2Y4MTM5MmQ0ZjY4YjRhODY1ZjE4ZWU=
